export const COUNTRY_MAP: Record<string, string> = {
    'タイ': 'Thailand',
    'ベトナム': 'Vietnam',
    'マレーシア': 'Malaysia',
    'インドネシア': 'Indonesia',
    'フィリピン': 'Philippines',
    '中国': 'China',
    '中国（香港）': 'Hong Kong',
    'カンボジア': 'Cambodia',
    'ラオス': 'Laos',
    'ミャンマー': 'Myanmar',
    'エジプト': 'Egypt',
    'ケニア': 'Kenya',
    '南アフリカ': 'South Africa',
    'エチオピア': 'Ethiopia',
    'タンザニア': 'Tanzania',
    'ナイジェリア': 'Nigeria',
    'UAE': 'UAE',
    'アラブ首長国連邦': 'UAE',
    'イスラエル': 'Israel',
    'トルコ': 'Turkey',
    '英国': 'UK',
    'フランス': 'France',
    'ドイツ': 'Germany',
    'オランダ': 'Netherlands',
    'スイス': 'Switzerland',
    'スペイン': 'Spain',
    'イタリア': 'Italy',
    'オーストリア': 'Austria',
    'ベルギー': 'Belgium',
    'ブラジル': 'Brazil',
    'アルゼンチン': 'Argentina',
    'チリ': 'Chile',
    'ペルー': 'Peru',
    'コロンビア': 'Colombia',
    'オーストラリア': 'Australia',
    'ニュージーランド': 'New Zealand',
    'United States': 'United States'
};

export const COUNTRY_JA_MAP: Record<string, string> = {
    'United States': 'アメリカ',
    'Canada': 'カナダ',
    'UAE': 'アラブ首長国連邦',
    'Australia': 'オーストラリア',
    'New Zealand': 'ニュージーランド',
    'Germany': 'ドイツ',
    'France': 'フランス',
    'UK': 'イギリス',
    'United Kingdom': 'イギリス',
    'Italy': 'イタリア',
    'Spain': 'スペイン',
    'Netherlands': 'オランダ',
    'Switzerland': 'スイス',
    'Austria': 'オーストリア',
    'Belgium': 'ベルギー',
    'Brazil': 'ブラジル',
    'Argentina': 'アルゼンチン',
    'Chile': 'チリ',
    'Peru': 'ペルー',
    'Colombia': 'コロンビア',
    'Kenya': 'ケニア',
    'South Africa': '南アフリカ',
    'Nigeria': 'ナイジェリア',
    'Egypt': 'エジプト',
    'Ethiopia': 'エチオピア',
    'Tanzania': 'タンザニア',
    'Israel': 'イスラエル',
    'Turkey': 'トルコ',
    'Thailand': 'タイ',
    'Vietnam': 'ベトナム',
    'Malaysia': 'マレーシア',
    'Indonesia': 'インドネシア',
    'Philippines': 'フィリピン',
    'China': '中国',
    'Hong Kong': '香港',
    'Cambodia': 'カンボジア',
    'Laos': 'ラオス',
    'Myanmar': 'ミャンマー',
};

export const SPECIALTY_MAP: Record<string, string> = {
    "内科": "Internal Medicine",
    "外科": "Surgery",
    "小児科": "Pediatrics",
    "産婦人科": "OB/GYN",
    "整形外科": "Orthopedics",
    "歯科": "Dental",
    "眼科": "Ophthalmology",
    "皮膚科": "Dermatology",
    "耳鼻科": "ENT",
    "精神科": "Psychiatry",
    "心療内科": "Psychosomatic",
    "泌尿器科": "Urology",
    "総合診療": "General Practice",
    "家庭医学": "Family Medicine",
    "健康診断": "Checkup",
    "人間ドック": "Full Checkup",
    "救急": "Emergency",
    "透析": "Dialysis",
    "リハビリテーション科": "Rehab",
    "脳神経外科": "Neurosurgery",
    "形成外科": "Plastic Surgery",
    "美容外科": "Cosmetic Surgery",
    "呼吸器内科": "Pulmonology",
    "循環器内科": "Cardiology",
    "循環器科": "Cardiology",
    "消化器内科": "Gastroenterology",
    "消化器科": "Gastroenterology",
    "婦人科": "Gynecology",
    "婦人科健診": "Gynecology Checkup",
    "レディースクリニック": "Women's Clinic",
    "人工透析": "Dialysis",
    "乳腺外科": "Breast Surgery",
    "乳腺": "Breast Surgery",
    "肛門科": "Proctology",
    "リウマチ科": "Rheumatology",
    "アレルギー科": "Allergy",
    "アレルギー": "Allergy",
    "麻酔科": "Anesthesiology",
    "病理診断科": "Pathology",
    "臨床検査科": "Clinical Laboratory",
    "救急科": "Emergency Medicine",
    "総合診療科": "General Practice",
    "一般診療": "General Practice",
    "一般医": "General Practitioner",
    "家庭医": "Family Doctor",
    "放射線科": "Radiology",
    "リハビリテーション": "Rehabilitation",
    "東洋医学": "Oriental Medicine",
    "漢方": "Kampo Medicine",
    "鍼灸": "Acupuncture",
    "メンズヘルス": "Men's Health",
    "性感染症": "STD/STI",
    "予防接種": "Vaccination",
    "ワクチン": "Vaccination",
    "各種ワクチン": "Vaccination",
    "渡航外来": "Travel Clinic",
    "トラベルクリニック": "Travel Clinic",
    "ペインクリニック": "Pain Clinic",
    "カイロプラクティック": "Chiropractic",
    "オステオパシー": "Osteopathy",
    "ホメオパシー": "Homeopathy",
    "自然療法": "Naturopathy",
    "心理療法": "Psychotherapy",
    "カウンセリング": "Counseling",
    "栄養指導": "Nutrition Counseling",
    "不妊治療": "Fertility Treatment",
    "体外受精": "IVF",
    "内視鏡": "Endoscopy",
    "物理療法": "Physiotherapy",
    "言語療法": "Speech Therapy",
    "作業療法": "Occupational Therapy",
    "訪問診療": "Home Visit",
    "往診": "House Call",
    "オンライン診療": "Telemedicine",
    "遠隔診療": "Telemedicine",
    "セカンドオピニオン": "Second Opinion",
    "発熱外来": "Fever Clinic",
    "PCR検査": "PCR Test",
    "抗原検査": "Antigen Test",
    "抗体検査": "Antibody Test",
    "外傷": "Trauma",
    "耳鼻咽喉科": "ENT",
    "泌尿器": "Urology"
};

export const CITY_MAP: Record<string, string> = {
    "バンコク": "Bangkok",
    "シラチャ": "Sriracha",
    "チェンマイ": "Chiang Mai",
    "プーケット": "Phuket",
    "サムイ島": "Samui",
    "パタヤ": "Pattaya",
    "ハノイ": "Hanoi",
    "ホーチミン": "Ho Chi Minh",
    "ダナン": "Da Nang",
    "クアラルンプール": "Kuala Lumpur",
    "ペナン": "Penang",
    "ジョホールバル": "Johor Bahru",
    "ジャカルタ": "Jakarta",
    "バリ": "Bali",
    "マニラ": "Manila",
    "セブ": "Cebu",
    "上海": "Shanghai",
    "北京": "Beijing",
    "広州": "Guangzhou",
    "大連": "Dalian",
    "蘇州": "Suzhou",
    "香港": "Hong Kong",
    "プノンペン": "Phnom Penh",
    "シェムリアップ": "Siem Reap",
    "ビエンチャン": "Vientiane",
    "ヤンゴン": "Yangon",
    "カイロ": "Cairo",
    "ナイロビ": "Nairobi",
    "ヨハネスブルグ": "Johannesburg",
    "アディスアベバ": "Addis Ababa",
    "ダルエスサラーム": "Dar es Salaam",
    "ラゴス": "Lagos",
    "ロンドン": "London",
    "パリ": "Paris",
    "デュッセルドルフ": "Dusseldorf",
    "ミュンヘン": "Munich",
    "フランクフルト": "Frankfurt",
    "アムステルダム": "Amsterdam",
    "ジュネーブ": "Geneva",
    "チューリッヒ": "Zurich",
    "バルセロナ": "Barcelona",
    "マドリード": "Madrid",
    "ミラノ": "Milan",
    "ローマ": "Rome",
    "ウィーン": "Vienna",
    "ブリュッセル": "Brussels",
    "サンパウロ": "Sao Paulo",
    "ブエノスアイレス": "Buenos Aires",
    "サンティアゴ": "Santiago",
    "リマ": "Lima",
    "ボゴタ": "Bogota",
    "シドニー": "Sydney",
    "メルボルン": "Melbourne",
    "ゴールドコースト": "Gold Coast",
    "パース": "Perth",
    "オークランド": "Auckland",
    "クライストチャーチ": "Christchurch",
    "ニューヨーク": "New York",
    "ロサンゼルス": "Los Angeles",
    "サンフランシスコ": "San Francisco",
    "サンノゼ": "San Jose",
    "ホノルル": "Honolulu",
    "シカゴ": "Chicago",
    "ヒューストン": "Houston",
    "ダラス": "Dallas",
    "アトランタ": "Atlanta",
    "ボストン": "Boston",
    "シアトル": "Seattle",
    "ワシントンD.C.": "Washington D.C.",
    "ラスベガス": "Las Vegas",
    "マイアミ": "Miami",
    "オーランド": "Orlando",
    "サンディエゴ": "San Diego",
    "デトロイト": "Detroit",
    "ナッシュビル": "Nashville",
    "コロンバス": "Columbus"
};

export const COUNTRY_CODES: Record<string, string> = {
    'インドネシア': 'id', 'カンボジア': 'kh', 'タイ': 'th',
    'フィリピン': 'ph', 'ベトナム': 'vn', 'マレーシア': 'my',
    'ミャンマー': 'mm', 'ラオス': 'la', '中国': 'cn',
    '中国（香港）': 'hk', 'カナダ': 'ca', 'アメリカ': 'us',
    'アルゼンチン': 'ar', 'コロンビア': 'co', 'チリ': 'cl',
    'ブラジル': 'br', 'ペルー': 'pe', 'イタリア': 'it',
    'オランダ': 'nl', 'オーストリア': 'at', 'スイス': 'ch',
    'スペイン': 'es', 'ドイツ': 'de', 'フランス': 'fr',
    'ベルギー': 'be', '英国': 'gb', 'オーストラリア': 'au',
    'ニュージーランド': 'nz', 'アラブ首長国連邦': 'ae',
    'エジプト': 'eg', 'エチオピア': 'et', 'ケニア': 'ke',
    'タンザニア': 'tz', 'ナイジェリア': 'ng', '南アフリカ': 'za',
    // Fallbacks
    'USA': 'us', 'UK': 'gb', 'UAE': 'ae', 'Singapore': 'sg', 'Hong Kong': 'hk', 'South Korea': 'kr', 'Taiwan': 'tw', 'India': 'in', 'Nepal': 'np', 'Mongolia': 'mn', 'Sri Lanka': 'lk', 'Mexico': 'mx', 'Saudi Arabia': 'sa', 'Israel': 'il', 'Qatar': 'qa', 'Ireland': 'ie', 'Hungary': 'hu', 'Russia': 'ru'
};
