import { readFileSync, writeFileSync } from 'fs';

const path = new URL('../src/data/clinics.json', import.meta.url);
const clinics = JSON.parse(readFileSync(path, 'utf8'));

const byId = new Map(clinics.map((clinic) => [clinic.id, clinic]));

function upsert(clinic) {
  const existing = byId.get(clinic.id);
  if (existing) {
    Object.assign(existing, clinic);
    return;
  }
  clinics.push(clinic);
  byId.set(clinic.id, clinic);
}

const phone88 = byId.get('88');
if (phone88) {
  phone88.phone = '087-789-150（日本語24時間）';
  phone88.phoneClean = '+85587789150';
}

for (const clinic of clinics) {
  if (clinic.website?.startsWith('http://')) {
    clinic.website = clinic.website.replace('http://', 'https://');
  }
}

const reviewed = '2026-08-16';

const additions = [
  {
    id: '269',
    nameJa: 'ラッフルズジャパニーズクリニック',
    nameEn: 'Raffles Japanese Clinic',
    continent: 'Asia',
    country: 'シンガポール',
    city: 'シンガポール',
    address: '585 North Bridge Road, Raffles Hospital, Singapore 188770',
    phone: '6311-1190（日本語）',
    phoneClean: '+6563111190',
    supportLevel: 'medical',
    website: 'https://rafflesj-clinic.com/',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Raffles%20Japanese%20Clinic%20585%20North%20Bridge%20Road%20Singapore',
    specialties: ['内科', '小児科', '皮膚科', '健康診断', '予防接種'],
    hoursDescription: '月〜金 9:00-18:30、土 9:00-13:00',
    japaneseSupportDetails: '日本人医師・歯科医・看護師・スタッフ常駐。診療は日本語。',
    emergencyAvailable: false,
    cashlessAvailable: true,
    notes: 'ラッフルズ病院内の日系クリニック。出典: 公式サイト',
    lastReviewedAt: reviewed,
    sourceName: 'rafflesj-clinic.com',
    timeZone: 'Asia/Singapore',
    lat: 1.301,
    lng: 103.854,
  },
  {
    id: '270',
    nameJa: 'シンガポール日本人会診療所',
    nameEn: 'Japanese Association Clinic Singapore',
    continent: 'Asia',
    country: 'シンガポール',
    city: 'シンガポール',
    address: '120 Adam Road, Singapore 289899',
    phone: '6467-0070（日本語） / 6469-6488',
    phoneClean: '+6564670070',
    supportLevel: 'medical',
    website: 'https://www.japanese-clinic.com.sg/',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Japanese%20Association%20Clinic%20120%20Adam%20Road%20Singapore',
    specialties: ['内科', '小児科', '心療内科', '健康診断', '予防接種'],
    hoursDescription: '月〜金 9:00-12:00 / 14:00-17:00、土 9:00-13:00',
    japaneseSupportDetails: '日本人医師および日本語対応医師が在籍。1985年開設の邦人向け診療所。',
    emergencyAvailable: false,
    cashlessAvailable: false,
    notes: '日本人会会員以外も利用可。出典: 公式サイト / 日本人会',
    lastReviewedAt: reviewed,
    sourceName: 'japanese-clinic.com.sg',
    timeZone: 'Asia/Singapore',
    lat: 1.3317,
    lng: 103.8142,
  },
  {
    id: '271',
    nameJa: 'サムスンソウル病院 国際診療センター',
    nameEn: 'Samsung Medical Center',
    continent: 'Asia',
    country: '韓国',
    city: 'ソウル',
    address: '81 Irwon-ro, Gangnam-gu, Seoul',
    phone: '02-3410-0200（国際診療）',
    phoneClean: '+82234100200',
    supportLevel: 'support',
    website: 'https://www.samsunghospital.com/',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Samsung%20Medical%20Center%20Seoul',
    specialties: ['総合病院', '内科', '外科', '救急'],
    hoursDescription: '要予約。救急は24時間',
    japaneseSupportDetails: '国際診療センターで通訳・外国人患者支援あり。日本語対応は事前確認を推奨。',
    emergencyAvailable: true,
    cashlessAvailable: true,
    notes: '出典: 病院公式サイト。受診前に日本語対応可否を確認してください。',
    lastReviewedAt: reviewed,
    sourceName: 'samsunghospital.com',
    timeZone: 'Asia/Seoul',
    lat: 37.4882,
    lng: 127.0856,
  },
  {
    id: '272',
    nameJa: 'ソウル峨山病院 国際診療センター',
    nameEn: 'Asan Medical Center',
    continent: 'Asia',
    country: '韓国',
    city: 'ソウル',
    address: '88 Olympic-ro 43-gil, Songpa-gu, Seoul',
    phone: '02-3010-5001（国際診療）',
    phoneClean: '+82230105001',
    supportLevel: 'support',
    website: 'https://eng.amc.seoul.kr/',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Asan%20Medical%20Center%20Seoul',
    specialties: ['総合病院', '内科', '外科', '救急'],
    hoursDescription: '要予約。救急は24時間',
    japaneseSupportDetails: '国際診療センターあり。日本語通訳は予約制の場合あり。',
    emergencyAvailable: true,
    cashlessAvailable: true,
    notes: '出典: 病院公式サイト。受診前に日本語対応可否を確認してください。',
    lastReviewedAt: reviewed,
    sourceName: 'amc.seoul.kr',
    timeZone: 'Asia/Seoul',
    lat: 37.5265,
    lng: 127.1083,
  },
  {
    id: '273',
    nameJa: 'セブランス病院',
    nameEn: 'Severance Hospital',
    continent: 'Asia',
    country: '韓国',
    city: 'ソウル',
    address: '50-1 Yonsei-ro, Seodaemun-gu, Seoul',
    phone: '1599-1004',
    phoneClean: '+8215991004',
    supportLevel: 'support',
    website: 'https://sev.severance.healthcare/',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Severance%20Hospital%20Seoul',
    specialties: ['総合病院', '内科', '外科', '救急'],
    hoursDescription: '要予約。救急は24時間',
    japaneseSupportDetails: '外国人患者支援・通訳あり。日本語は事前予約を推奨。',
    emergencyAvailable: true,
    cashlessAvailable: true,
    notes: '延世大学医療院。出典: 病院公式サイト。',
    lastReviewedAt: reviewed,
    sourceName: 'severance.healthcare',
    timeZone: 'Asia/Seoul',
    lat: 37.5623,
    lng: 126.9408,
  },
  {
    id: '274',
    nameJa: 'ソウル大学病院',
    nameEn: 'Seoul National University Hospital',
    continent: 'Asia',
    country: '韓国',
    city: 'ソウル',
    address: '101 Daehak-ro, Jongno-gu, Seoul',
    phone: '02-2072-2114',
    phoneClean: '+82220722114',
    supportLevel: 'support',
    website: 'https://www.snuh.org/',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Seoul%20National%20University%20Hospital',
    specialties: ['総合病院', '内科', '外科', '救急'],
    hoursDescription: '要予約。救急は24時間',
    japaneseSupportDetails: '外国人向け診療窓口あり。日本語対応は事前確認を推奨。',
    emergencyAvailable: true,
    cashlessAvailable: false,
    notes: '出典: 病院公式サイト / 在韓公館案内で言及される主要病院。',
    lastReviewedAt: reviewed,
    sourceName: 'snuh.org',
    timeZone: 'Asia/Seoul',
    lat: 37.5796,
    lng: 126.999,
  },
  {
    id: '275',
    nameJa: '台安医院',
    nameEn: 'Taiwan Adventist Hospital',
    continent: 'Asia',
    country: '台湾',
    city: '台北',
    address: '台北市松山區八德路二段424號',
    phone: '02-2771-8151',
    phoneClean: '+886227718151',
    supportLevel: 'support',
    website: 'https://www.tahsda.org.tw/jp/',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Taiwan%20Adventist%20Hospital%20Taipei',
    specialties: ['総合病院', '内科', '外科', '国際診療'],
    hoursDescription: '国際医療センターあり。要予約',
    japaneseSupportDetails: '国際医療センターに日本語ページあり。日本語対応の特別外来あり。',
    emergencyAvailable: true,
    cashlessAvailable: true,
    notes: '出典: 台安医院公式日本語ページ。',
    lastReviewedAt: reviewed,
    sourceName: 'tahsda.org.tw',
    timeZone: 'Asia/Taipei',
    lat: 25.0482,
    lng: 121.5486,
  },
  {
    id: '276',
    nameJa: '國泰綜合醫院',
    nameEn: 'Cathay General Hospital',
    continent: 'Asia',
    country: '台湾',
    city: '台北',
    address: '台北市大安區仁愛路四段280號',
    phone: '02-2708-2121',
    phoneClean: '+886227082121',
    supportLevel: 'support',
    website: 'https://www.cgh.org.tw/',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cathay%20General%20Hospital%20Taipei',
    specialties: ['総合病院', '内科', '外科', '救急'],
    hoursDescription: '要予約。救急あり',
    japaneseSupportDetails: '邦人利用実績のある総合病院。日本語対応は部署により異なるため事前確認を推奨。',
    emergencyAvailable: true,
    cashlessAvailable: true,
    notes: '出典: 病院公式サイト。',
    lastReviewedAt: reviewed,
    sourceName: 'cgh.org.tw',
    timeZone: 'Asia/Taipei',
    lat: 25.0375,
    lng: 121.554,
  },
  {
    id: '277',
    nameJa: 'クイーンズ・メディカル・センター',
    nameEn: "The Queen's Medical Center",
    continent: 'North America',
    country: 'United States',
    city: 'ハワイ（ホノルル）',
    address: '1301 Punchbowl Street, Honolulu, HI 96813',
    phone: '808-538-9011',
    phoneClean: '+18085389011',
    supportLevel: 'support',
    website: 'https://www.queens.org/',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Queens%20Medical%20Center%20Honolulu',
    specialties: ['総合病院', '救急', '内科', '外科'],
    hoursDescription: '救急24時間',
    japaneseSupportDetails: '総合病院。日本語を含む通訳サービスを手配できる場合あり。事前確認を推奨。',
    emergencyAvailable: true,
    cashlessAvailable: false,
    notes: 'ホノルルの基幹病院。出典: 病院公式サイト。',
    lastReviewedAt: reviewed,
    sourceName: 'queens.org',
    timeZone: 'Pacific/Honolulu',
    lat: 21.3076,
    lng: -157.8553,
  },
  {
    id: '278',
    nameJa: 'クアキニ・メディカル・センター',
    nameEn: 'Kuakini Medical Center',
    continent: 'North America',
    country: 'United States',
    city: 'ハワイ（ホノルル）',
    address: '347 N Kuakini Street, Honolulu, HI 96817',
    phone: '808-536-2236',
    phoneClean: '+18085362236',
    supportLevel: 'support',
    website: 'https://www.kuakini.org/',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kuakini%20Medical%20Center%20Honolulu',
    specialties: ['総合病院', '内科', '外科'],
    hoursDescription: '要確認',
    japaneseSupportDetails: '日系コミュニティと縁の深い病院。日本語対応は部署により異なるため事前確認を。',
    emergencyAvailable: false,
    cashlessAvailable: false,
    notes: '出典: 病院公式サイト。',
    lastReviewedAt: reviewed,
    sourceName: 'kuakini.org',
    timeZone: 'Pacific/Honolulu',
    lat: 21.3215,
    lng: -157.8578,
  },
  {
    id: '279',
    nameJa: 'アメリカン・ホスピタル・ドバイ',
    nameEn: 'American Hospital Dubai',
    continent: 'Africa & Middle East',
    country: 'UAE',
    city: 'Dubai',
    address: 'Oud Metha Road, Dubai',
    phone: '+971-4-377-5500',
    phoneClean: '+97143775500',
    supportLevel: 'support',
    website: 'https://www.ahdubai.com/',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=American%20Hospital%20Dubai',
    specialties: ['総合病院', '救急', '内科', '外科'],
    hoursDescription: '救急24時間',
    japaneseSupportDetails: '英語対応の国際病院。日本語はコーディネーター手配の場合あり。事前確認を推奨。',
    emergencyAvailable: true,
    cashlessAvailable: true,
    notes: '出典: 病院公式サイト。日本語常駐ではないため受診前に確認してください。',
    lastReviewedAt: reviewed,
    sourceName: 'ahdubai.com',
    timeZone: 'Asia/Dubai',
    lat: 25.2362,
    lng: 55.318,
  },
];

for (const clinic of additions) {
  upsert(clinic);
}

writeFileSync(path, `${JSON.stringify(clinics, null, 2)}\n`);
console.log('clinics', clinics.length);
